version: 2
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk:latest
    working_directory: ~/cosmiccalc
    steps:
      - checkout
      - run:
          name: create GCP key file
          command: echo ${GCP_KEY} > ~/cosmiccalc/gcp_key.json
      - run:
          name: authorize SDK
          command: gcloud auth activate-service-account --key-file ~/cosmiccalc/gcp_key.json
      - run:
          name: clean up GCP key file
          command: rm ~/cosmiccalc/gcp_key.json
      - run:
          name: set project
          command: gcloud --quiet config set project cosmiccalc
      - run:
          name: stage app.yaml
          command: mv ~/cosmiccalc/.circleci/app.yaml ~/cosmiccalc/app.yaml
      - run:
          name: replace paths
          command: |
            sed -i "s#${GH_PATH}#${GAE_PATH}#g" ~/cosmiccalc/index.html
            sed -i "s#${GH_PATH}#${GAE_PATH}#g" ~/cosmiccalc/js/cosmicalc.js
      - deploy:
          command: gcloud --quiet app deploy ~/cosmiccalc/app.yaml -v 1
  release:
    docker:
      - image: golang:latest
    working_directory: ~/cosmiccalc
    steps:
      - checkout
      - run:
          name: install zip
          command: apt-get update && apt-get install -y --no-install-recommends zip
      - run:
          name: install ghr
          command: go get -u github.com/tcnksm/ghr
      - run:
          name: extract release date
          command: sed -n 's#.*LAST_MODIFIED *= *"\(.*\)".*#\1#p' ~/cosmiccalc/js/cosmicalc.js > ~/cosmiccalc/.circleci/release_date
      - run:
          name: zip files
          command: zip -r9q ~/cosmiccalc/cosmiccalc.zip ~/cosmiccalc/*
      - run:
          name: create GitHub Release
          command: ghr --replace $(cat ~/cosmiccalc/.circleci/release_date) ~/cosmiccalc/cosmiccalc.zip
workflows:
  version: 2
  deploy-release:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
      - release:
          filters:
            branches:
              only: circleci
